services:
  app:
    container_name: ketard-ai
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ket0x4/ketard-ai:latest
    restart: on-failure
    volumes:
      - type: bind
        source: ./settings.json
        target: /app/settings.json
